---
title: "Exercício 03"
subtitle: "Tópicos Avançados em Modelagem Ambiental - CAP INPE"
date: 2025-10-20
author: Pedro Borges
lang: pt-BR
format: 
  html:
    toc: true
    number-sections: true
    fig-cap-location: margin
    code-links:
      - text: Repositório
        icon: github
        href: https://www.github.com/pabsantos/tama
execute:
  fig-keep: last
  warning: false
---

## Introdução

O presente relatório apresenta a aplicação de uma Rede Neural Recorrente (RNN) do tipo LSTM (*Long Short-Term Memory*) para modelar e prever uma série temporal da precipitação diária acumulada. A análise foi elaborada com auxílio das seguintes bibliotécas:

```{python}
import os
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input
```

## Dados

Os dados utilizados foram coletados do [Mapa Interativo da Rede Observacional para Monitoramento de Risco de Desastres Naturais do Cemaden](https://mapainterativo.cemaden.gov.br). Foram extraídos os dados de estações pluviométricas da cidade de São Paulo, considerando o período entre 07/2024 e 06/2025. Decidiu-se por focar a análise dos dados coletados pela estação "Centro".

O atributo "datahora" foi dividido em duas colunas distintas, possibilitando o cálculo da precipitação acumulada por dia. Originalmente, o registro dos dados foi realizado em uma frequência horária quando o valor da precipitação foi 0.00 mm e em momentos de precipitação acima de 0, observou-se que o registro foi realizado em uma frequência de 10 minutos. Datas sem registro de dados foram substituídas pelo valor 0.

```{python}
data_folder = "../data/"
file_list = os.listdir(data_folder)
path_list = [data_folder + file for file in file_list]
df_list = [pd.read_csv(file, sep=";") for file in path_list]
df_precipitacao = pd.concat(df_list)

df_precipitacao[["data", "hora"]] = df_precipitacao.datahora.str.split(" ", expand=True)
df_precipitacao.valorMedida = pd.to_numeric(
    df_precipitacao.valorMedida.str.replace(",", ".")
)

df_diario = (
    df_precipitacao[df_precipitacao.nomeEstacao == "Centro "]
    .groupby("data")
    .agg(acumulado=("valorMedida", "sum"))
    .reset_index()
)

df_diario.data = pd.to_datetime(df_diario.data)

data_inicial = df_diario.data.min()
data_final = df_diario.data.max()
date_range = pd.date_range(start=data_inicial, end=data_final, freq="D")
df_base = pd.DataFrame({"data": date_range})
df_diario_clean = pd.merge(df_base, df_diario, how="left", on="data").fillna(0)
df_diario_clean
```

## Modelagem

O primeiro passo foi realizar a normalização dos dados ($[0, 1]$) de precipitação. Em seguida, a série temporal foi transformada em conjuntos de entrada ($X$) e saída ($Y$), dentro do conceito de *look-back* com 30 dias. Ou seja, a rede LSTM usará os dados de precipitação dos 30 dias anteriores como entrada para prever a precipitação do dia seguinte. Os dados foram organizados para um formato 3D exigido pelo modelo: `[amostras, look_back, características]`

```{python}
scaler = MinMaxScaler(feature_range=(0, 1))
df_normalizado = scaler.fit_transform(df_diario_clean[["acumulado"]])

def create_dataset(data, look_back):
    X, Y = [], []
    for i in range(len(data) - look_back - 1):
        a = data[i:(i + look_back), 0]
        X.append(a)
        Y.append(data[i + look_back, 0])
    return np.array(X), np.array(Y)

look_back = 30

X, Y = create_dataset(df_normalizado, look_back)
tamanho_treino = int(len(X) * 0.70)
X_treino, X_teste = X[0:tamanho_treino], X[tamanho_treino:len(X)]
Y_treino, Y_teste = Y[0:tamanho_treino], Y[tamanho_treino:len(Y)]
X_treino = np.reshape(X_treino, (X_treino.shape[0], X_treino.shape[1], 1))
X_teste = np.reshape(X_teste, (X_teste.shape[0], X_teste.shape[1], 1))
```

Em seguida, o modelo foi aplicado com input de (30, 1) - 30 dias de look-back e 1 variável (precipitação acumulada). Foi selecionada uma dimensão de 50 unidades para a camada LSTM e 1 neurônio na camada de saída. A compilação foi realizada usando o MSE como função de perda.

```{python}
input_shape_data = (look_back, 1)

modelo = Sequential([
    Input(shape=input_shape_data),
    LSTM(50),
    Dense(1)
])

modelo.summary()
modelo.compile(loss='mean_squared_error', optimizer='adam')
```

No fit do modelo, dois hiperparâmetros devem ser ajustados: o *batch* e o *epochs*. Epoch define quantas vezes o algoritmo de aprendizado passará por todo o conjunto de dados de treinamento. O valor de 10 significa que a rede LSTM processará todo o conjunto de dados de treinamento 10 vezes para aprender os padrões de precipitação. O Batch Size é o número de amostras de treinamento que são passadas pela rede neural de uma só vez. O 32 significa que a rede processará 32 amostras de precipitação por vez antes de realizar uma atualização de peso.

```{python}
#| output: false

historico = modelo.fit(
    X_treino,
    Y_treino, 
    epochs=10, 
    batch_size=32, 
    verbose=1
)


```

A avaliação final do modelo na base de teste foi realizada utilizando a Raiz do Erro Quadrático Médio (RMSE).

```{python}
#| output: false

previsoes_treino = modelo.predict(X_treino)
previsoes_teste = modelo.predict(X_teste)

previsoes_treino_reais = scaler.inverse_transform(previsoes_treino)
previsoes_teste_reais = scaler.inverse_transform(previsoes_teste)
Y_teste_reais = scaler.inverse_transform(Y_teste.reshape(-1, 1))

rmse = np.sqrt(mean_squared_error(Y_teste_reais, previsoes_teste_reais))
```

Seu valor resultou em `{python} f"{rmse:.2f}"`, um desempenho pior comparado ao modelo de random forest utilizado no exercício anterior.

## Conclusão

Esse trabalho apresentou brevemente a aplicação de um modelo RNN com base em uma série temporal de precipitação acumulada diária, coletada em uma estação do centro da cidade de São Paulo. Esse modelo ainda necessita de mais testes com outros hiperparâmetros e uma amostra maior para aprimorar o seu desempenho.